services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: passwd123
      POSTGRES_USER: admin
      POSTGRES_DB: shop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shop"]
      interval: 4s
      # timeout: 5s
      retries: 5
      start_period: 4s
  web:
    build: ./
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://admin:passwd123@postgresql:5432/shop
      # - SECRET_KEY=your_secret_key
      - DEBUG=False
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py create_default_user && gunicorn shopApp.wsgi:application --bind 0.0.0.0:8000 --workers 3"