# Generated by Django 5.1.6 on 2025-03-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='default',
        ),
    ]
