# Generated by Django 5.1.6 on 2025-04-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_billingaddress_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
