# Generated by Django 5.1.6 on 2025-04-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_about_brand_sellerapplication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
    ]
