# Generated by Django 5.1.6 on 2025-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_is_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='desired_role',
            field=models.CharField(choices=[('courier', 'Courier'), ('manager', 'Manager')], default='courier', max_length=20),
        ),
    ]
